/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Helena Mansur (https://sketchfab.com/helena.rmansur2)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/adventurers-rest-7310c87b2eb147d88cb7e482ed611adc
title: Adventurer's rest
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    escudo: THREE.MeshStandardMaterial
    espada: THREE.MeshStandardMaterial
    arvere: THREE.MeshStandardMaterial
  }
}

export function Tree(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/adventurers_rest.glb"
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        userData={{ name: "root" }}
        scale={0.5}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "GLTF_SceneRootNode" }}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.arvere}
            userData={{ name: "Object_8" }}
            position={[-0.44, 0, -4.58]}
            rotation={[0, 0.68, 0]}
          />
        </group>
      </group>
    </group>
  )
}
